=== vaibhavivinchhi/XML/Assignment 2/1.dtd
<!ELEMENT student (personal_info)>
<!ELEMENT personal_info (rollno,name,address,mobile,Dob,age,Qualification)>
<!ELEMENT rollno (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT mobile (#PCDATA)>
<!ELEMENT Dob (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT Qualification (#PCDATA)>

=== vaibhavivinchhi/XML/Assignment 2/1.xml
<?xml version="1.0"?>
	<!DOCTYPE student SYSTEM "1.dtd">
	<student>
		<personal_info>
			<rollno>113</rollno>
			<name>vaibhavi</name>
			<address>Ahmedabad</address>
			<mobile>1234567890</mobile>
			<Dob>06/03/2006</Dob>
			<age>18</age>
			<Qualification>abc</Qualification>
		</personal_info>
	</student>
