=== vaibhavivinchhi/XML/Assignment 2/4.dtd
<!ELEMENT student (stud_det)>
<!ELEMENT stud_det (student_name,personal_info,result)>
<!ELEMENT personal_info (address,birthdate,gender,Mobileno,Address)>
<!ELEMENT gender (Male,Female)>
<!ELEMENT result (total,percentage,grade)>
<!ELEMENT grade (pass|first|dist|second|fail)>		
<!ELEMENT student_name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT birthdate (#PCDATA)>
<!ELEMENT Male (#PCDATA)>
<!ELEMENT Female (#PCDATA)>
<!ELEMENT Mobileno (#PCDATA)>
<!ELEMENT Address (#PCDATA)>
<!ELEMENT total (#PCDATA)>
<!ELEMENT percentage (#PCDATA)>
<!ELEMENT pass (#PCDATA)>
<!ELEMENT first (#PCDATA)>
<!ELEMENT dist (#PCDATA)>
<!ELEMENT second (#PCDATA)>
<!ELEMENT fail (#PCDATA)>

=== vaibhavivinchhi/XML/Assignment 2/4.xml
<?xml version="1.0"?>
	<!DOCTYPE student SYSTEM "4.dtd">
	<student>
		<stud_det>
			<student_name></student_name>
			<personal_info>
				<address></address>
				<birthdate></birthdate>
				<gender>
					<Male></Male>
					<Female></Female>
				</gender>
				<Mobileno></Mobileno>
				<Address></Address>
			</personal_info>
			<result>
				<total></total>
				<percentage></percentage>
				<grade>
					<pass></pass>
				</grade>
			</result>
		</stud_det>
	</student>
