=== vaibhavivinchhi/XML/Assignment 2/6.dtd
<!ELEMENT student (stud_det)>
<!ELEMENT stud_det (Name,ID,Plan)>
<!ELEMENT Name (fname,lname)>
<!ELEMENT Plan (courses*)>
<!ELEMENT courses (course)>
<!ELEMENT course (name,shortname,record*)>
<!ELEMENT record (grade,date)>
<!ELEMENT fname (#PCDATA)>
<!ELEMENT lname (#PCDATA)>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT shortname (#PCDATA)>
<!ELEMENT grade (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ATTLIST courses year CDATA #REQUIRED>

=== vaibhavivinchhi/XML/Assignment 2/6.xml
<?xml version="1.0"?>
	<!DOCTYPE student SYSTEM "6.dtd">
		<student>
			<stud_det>
				<Name>
					<fname></fname>
					<lname></lname>
				</Name>
				<ID></ID>
				<Plan>
					<courses year="">
						<course>
							<name></name>
							<shortname></shortname>
							<record>
								<grade></grade>
								<date></date>
							</record>
						</course>
					</courses>
				</Plan>
			</stud_det>
		</student>
