=== vaibhavivinchhi/XML/Assignment 2/7.dtd
<!ELEMENT Email (Email_det)>
		<!ELEMENT Email_det (from,to,content,courses)>
		<!ELEMENT content (#PCDATA|person|exercises)*>
		<!ELEMENT exercises (exercise*)>
		<!ELEMENT exercise (topic,description)>
		<!ELEMENT from (#PCDATA)>
		<!ELEMENT to (#PCDATA)>
		<!ELEMENT person (#PCDATA)>
		<!ELEMENT topic (#PCDATA)>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT courses (#PCDATA)>

=== vaibhavivinchhi/XML/Assignment 2/7.xml
<?xml version="1.0"?>
	<!DOCTYPE Email SYSTEM "7.dtd">
	<Email>
		<Email_det>
			<from></from>
			<to></to>
			<content>
				<person></person>
				<exercises>
					<exercise>
						<topic></topic>
						<description></description>
					</exercise>
				</exercises>
			</content>
			<courses></courses>
		</Email_det>
	</Email>
