=== vaibhavivinchhi/XML/Assignment 2/8.dtd
<!ELEMENT student (stud_det)>
		<!ELEMENT stud_det (rollno,name,marks,rank)>
		<!ELEMENT marks (web_technologies,XML,J2EE,NS)>
		<!ELEMENT rollno (#PCDATA)>
		<!ELEMENT name (#PCDATA)>
		<!ELEMENT web_technologies (#PCDATA)>
		<!ELEMENT XML (#PCDATA)>
		<!ELEMENT J2EE (#PCDATA)>
		<!ELEMENT NS (#PCDATA)>
		<!ELEMENT rank (#PCDATA)>

=== vaibhavivinchhi/XML/Assignment 2/8.xml
<?xml version="1.0"?>
	<!DOCTYPE student SYSTEM "8.dtd">
	<student>
		<stud_det>
			<rollno></rollno>
			<name></name>
			<marks>
				<web_technologies></web_technologies>
				<XML></XML>
				<J2EE></J2EE>
				<NS></NS>
			</marks>
			<rank></rank>
		</stud_det>
	</student>
